server:
  port: 8081
  tomcat:
    max-http-form-post-size: 2147483648 # 2GB

springdoc:
  api-docs:
    enabled: true

popp-server:
  url: wss://popp.dev.poppservice.de:443/popp/practitioner/api/v1/token-generation-ehc
connector:
  end-point-url: ${CONNECTOR_END_POINT_URL:http://ti-konnektor/cardservice}

zeta:
  client:
    disableServerValidation: ${ZETA_CLIENT_DISABLE_SERVER_VALIDATION:true}
  authentication.smb:
    alias: ${ZETA_AUTHENTICATION_SMB_ALIAS:alias}
    keyfile: ${ZETA_AUTHENTICATION_SMB_KEYFILE:docker/zeta/smcb-private/smcb_private.p12}
    password: ${ZETA_AUTHENTICATION_SMB_PASSWORD:00}

card-reader:
  name:

virtual-card:
  image-file:
