spring:
  config:
    import:
      - "classpath:contact-based-scenarios.yaml"
      - "classpath:open-egk-scenarios.yaml"
      - "classpath:contact-less-scenarios.yaml"

server:
  port: 8081
  tomcat:
    max-http-form-post-size: 2147483648 # 2GB

springdoc:
  api-docs:
    enabled: true

# obtain the Rise URL via the "Gematik-Anfrageportal" and configure it here
popp-server:
  url: wss://popp-zeta-ingress:443/ws
connector:
  end-point-url: ${CONNECTOR_END_POINT_URL:http://ti-konnektor/cardservice}

zeta:
  client:
    disableServerValidation: ${ZETA_CLIENT_DISABLE_SERVER_VALIDATION:true}
  authentication.smb:
    alias: ${ZETA_AUTHENTICATION_SMB_ALIAS:alias}
    keyfile: ${ZETA_AUTHENTICATION_SMB_KEYFILE:docker/zeta/smcb-private/smcb_private.p12}
    password: ${ZETA_AUTHENTICATION_SMB_PASSWORD:00}

card-reader:
  name:

virtual-card:
  image-file:
